### ISSUE TITLE
PLAY上更新4.6.9后，卡开机。。。。。

### ISSUE THREAD

**Issue by caliban511** [Tornaco/X-APM#11]
如题。
红米note4X，MIUI9.2.1稳定版俄罗斯版。
酷安评论区有相同案例。
大佬这个问题还修复不？不修的话我就自己改4.6.8的版本号用下去了，省的PLAY老是提示更新。
当然，还是希望能继续更新下去，挺好的软件。

**Comment by Tornaco** [comment]
@caliban511 会有修复。稍等待一两天。

**Comment by Tornaco** [comment]
麻烦帮忙试试新版： https://github.com/Tornaco/X-APM/releases/download/4.7.0-BETA/app-release-stable-play.apk
多谢！

**Comment by caliban511** [comment]
感谢修复。这个版本重启后正常开机，期待正式版。
