### ISSUE TITLE
gcm代收问题

### ISSUE THREAD

**Issue by yanyumihuang** [Tornaco/X-APM#120]
首先非常感谢开发者开发了这个功能，但现在还存在着一些问题，首先就是消息的重复通知，比如别人给我发了一条，可以成功通过gcm代收，得到通知，但稍后会再来一条，也就是会重复通知。机型一加三，官方八点0用了黑域和写轮眼自己绿色守护。我个人猜测原因是作者通过提取tencent .com来获取类似通知然后代收，但实际上在通知中有两条tencent .com这样就造成了两条信息的通知

**Comment by Tornaco** [comment]
@renshreng 重复通知是因为暂时无法发送阅读回执，如果大家觉得这个方案还不错的话，后续会继续优化。

**Comment by NBlackQIE** [comment]
发现开了gcm代收和乖巧模式之后微信会在后台留core service和notify service，但没有丢入缓存中。在权限设置里尝试关闭后台服务之后微信全部服务都丢到缓存里了，gcm也能收到消息，但是进入微信却不能收发消息。

**Comment by Tornaco** [comment]
@NBlackQIE 好，有时间我试试。。

**Comment by fhxu** [comment]
我想知道怎么用代收接收google应用的消息，如youtube,gmail等
现在代收模式接收微信正常

**Comment by renshreng** [comment]
这个方案非常不错，因为基本上可以保证微信不丢消息，不用再管微信在不在后台，作为一个妻管严，觉得十分必要。哈哈，作者也可以看酷安上对这个功能的反馈，非常好😊😊😌

**Comment by tfytli** [comment]
@Tornaco GCM代收很好用，就是有个问题，在电脑上登陆微信的时候，手机端依然一直在提醒。能不能提供一个选项关闭手机端的提醒或者默认不提醒，就像微信一样。
