### ISSUE TITLE
划卡强退 ，不起作用。

### ISSUE THREAD

**Issue by qiuyouxin** [Tornaco/X-APM#126]
1. What happened（现象）:划卡强退，不起作用。 QQ为例， 加入功能，划卡强退、自启、关联启动。 我开启调试后，按相关操作后，在对应目录没有日志文件夹trace和日志文件。 所以直接提取xposed installer 的日志。

2. Xposed logs（日志）:
[error.log](https://github.com/Tornaco/X-APM/files/1912646/error.log)

3. Device info（设备信息）: HTC ，5.02

4. Frequency（出现频率）: 总是不起作用。

5. App version（版本）: 5.01 play

**Comment by Tornaco** [comment]
@qiuyouxin 感谢反馈，日志截取很规范！请等新版本的fix。

**Comment by Tornaco** [comment]
可能的原因：
HTC 5.0 ROM最近任务管理 负责的包为```com.htc.lockscreen```，而不是```com.android.systemui```。
在代码里做了兼容，需要等待测试结果，版本：https://github.com/Tornaco/X-APM/releases/tag/5.0.2-BETA

**Comment by qiuyouxin** [comment]
感谢辛苦调整。

**Comment by Tornaco** [comment]
好的。
