### ISSUE TITLE
和平安银行APP冲突，闪退

### ISSUE THREAD

**Issue by 250662772** [Tornaco/X-APM#131]
刚开始以为是框架的冲突，后台把此插件卸载，平安银行可以打开了，请作者排查下原因，平安银行下载地址https://b.pingan.com.cn/station/activity/download/app/index.html?outerid=ou0000011&cid=ci0000020&downapp_id=AM001000224

**Comment by lonely720** [comment]
是奥利奥吗，如果是，可以考虑下xposed版本改成beta2，我用beta3也会导致平安银行app闪退，换成beta2就莫名好了

**Comment by keith-xiong** [comment]
哪里有beta3, beta2 不是编译报错吗？

发自极邮<http://jadenine.cn>手机客户端
