### ISSUE TITLE
后台模糊会失效oneplus5 8.0氧os

### ISSUE THREAD

**Issue by zjcjgjj** [Tornaco/X-APM#15]
算是类原生rom了，但是后台模糊经常失效，后台打开多了，往后翻页找到后台模糊的app发现失效了…

**Comment by Tornaco** [comment]
@yinheng ASAP.

**Comment by zjcjgjj** [comment]
啥时候可以修复好，修复好了我可以测试一下，老是模糊失效有点头疼

**Comment by Tornaco** [comment]
Fixed @zjcjgjj  Since 5.0.6-BETA
