### ISSUE TITLE
乖巧模式感觉有点奇怪了

### ISSUE THREAD

**Issue by NBlackQIE** [Tornaco/X-APM#150]
更新了5.0.2后对微信打开应用锁然后丢进乖巧模式中（怕乖巧模式下微信容易被其他应用挤出缓存所以把微信丢进了后台常驻），微信正常在缓存里待了两天，然后就肆意地跑出来吃内存了。刚开始还以为是绿色化与乖巧冲突了，逐一应用排查后发现并没有问题，尝试把应用锁关闭后微信又正常乖乖地待在缓存了…（微信就这么皮的吗）
现在看起来貌似应用锁与乖巧模式冲突了？？
3. Device info（设备信息）: ``SONY X Performance Android6.0```

4. Frequency（出现频率）: ```Sometimes```

5. App version（版本）: ```5.02-RELEASE```

**Comment by Tornaco** [comment]
然后就肆意地跑出来吃内存了
这个是 发现 微信 启动后台服务了吗？

**Comment by NBlackQIE** [comment]
是的，core service和notify service这两个吃了将近300M内存，缓存里还有70M左右的微信缓存

**Comment by Tornaco** [comment]
@NBlackQIE 是不是对微信加了  关联启动规则？

**Comment by Tornaco** [comment]
@keith-xiong 乱七八糟的。。

**Comment by zzw6776** [comment]
@NBlackQIE 问下 后台常驻用什么实现的。

**Comment by NBlackQIE** [comment]
@zzw6776狂点版本号吧好像…

**Comment by Tornaco** [comment]
Fixed
