### ISSUE TITLE
建议加入屏蔽FC 弹窗的功能

### ISSUE THREAD

**Issue by Maolaohei** [Tornaco/X-APM#151]
用TIM经常弹出FC,但不影响正常的使用.
以前的自定义的rom里有这个功能,不知道现在为啥没了.

**Comment by keith-xiong** [comment]
Don't crash me 这个模块，即使应用FC也可以不闪退

**Comment by Maolaohei** [comment]
我使用的应用(因为屏蔽了部分组件)偶尔会FC,点击后也不会闪退,也就是仅仅弹出FC这个对话框而已,但是这个fc对话框看着烦.

**Comment by Tornaco** [comment]
@keith-xiong 试试新版的权限里的显示fc
