### ISSUE TITLE
如何编译带有GCM代收器的版本？

### ISSUE THREAD

**Issue by xseven007** [Tornaco/X-APM#153]
请问作者，如何编译带有GCM代收器的版本？我在build_var_config和自选编译里面没有找到相关模块的选取方法

**Comment by Tornaco** [comment]
@xseven007 长按版本号可以强制使用这个功能。
过几天可以支持自定义编译。

**Comment by xseven007** [comment]
那么请问一下，编译时出现：
> Task :app:compileReleaseJavaWithJavac 
/opt/src/X-APM/app/src/main/java/github/tornaco/xposedmoduletest/util/OSUtil.java:6: error: cannot find symbol
import android.os.SystemProperties;
                 ^
  symbol:   class SystemProperties
  location: package android.os
/opt/src/X-APM/app/src/main/java/github/tornaco/xposedmoduletest/ui/adapter/MultipleCheckableAdapter.java:7: error: package com.android.internal.widget does not exist
import com.android.internal.widget.RecyclerView;
                                  ^
/opt/src/X-APM/app/src/main/java/github/tornaco/xposedmoduletest/ui/adapter/MultipleCheckableAdapter.java:19: error: package RecyclerView does not exist
    public final class MultipleCheckBoxViewHolder extends RecyclerView.ViewHolder {
                                                                      ^
/opt/src/X-APM/app/src/main/java/github/tornaco/xposedmoduletest/ui/adapter/MultipleCheckableAdapter.java:21: error: cannot find symbol
        private RecyclerView checkboxContainer;
                ^
  symbol:   class RecyclerView
  location: class MultipleCheckableAdapter.MultipleCheckBoxViewHolder
/opt/src/X-APM/app/src/main/java/github/tornaco/xposedmoduletest/ui/adapter/ComponentReplacementListAdapter.java:25: error: cannot find symbol
import github.tornaco.xposedmoduletest.loader.GlideApp;
                                             ^
  symbol:   class GlideApp
  location: package github.tornaco.xposedmoduletest.loader
/opt/src/X-APM/app/src/main/java/github/tornaco/xposedmoduletest/xposed/app/XAshmanManager.java:10: error: cannot find symbol
import android.os.ServiceManager;
                 ^
  symbol:   class ServiceManager
  location: package android.os
/opt/src/X-APM/app/src/main/java/github/tornaco/xposedmoduletest/ui/adapter/BlockRecord2ListAdapter.java:20: error: cannot find symbol
import github.tornaco.xposedmoduletest.loader.GlideApp;
                                             ^
  symbol:   class GlideApp
  location: package github.tornaco.xposedmoduletest.loader
/opt/src/X-APM/app/src/main/java/github/tornaco/xposedmoduletest/ui/adapter/PermissionAppsAdapter.java:24: error: cannot find symbol
import github.tornaco.xposedmoduletest.loader.GlideApp;
导致无法编译，是因为没有安装什么东西嘛，我确认安装了SDK26，SDK27，NDK也装了的。

**Comment by xseven007** [comment]
把android.jar覆盖后编译成功了，但是发现修改减少组件的时候编译出来的apk文件并没有减小体积，似乎选择性编译组件只是把不需要的组件隐藏起来？并没有真正的去掉？

**Comment by Tornaco** [comment]
@xseven007 对。
如果要去掉只能手动删除。

**Comment by Tornaco** [comment]
@xseven007 需要配置Hidden API 参考连接：https://github.com/anggrayudi/android-hidden-api （本项目使用的是v26版本，代码目录hiddenapi下已经包含，因此你可以看下左边给的配置链接，直接用hiddenapi下的android.jar进行配置）。

**Comment by xseven007** [comment]
@Tornaco 最新的commit编译的时候出现
FAILURE: Build failed with an exception.

* Where:
Build file '/opt/src/X-APM/x-apm-base/build.gradle' line: 110

* What went wrong:
A problem occurred evaluating project ':x-apm-base'.
> /opt/src/X-APM/local.properties (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
似乎缺少/opt/src/X-APM/local.properties这个文件？

**Comment by xseven007** [comment]
@Tornaco 最新的commit编译的时候出现
FAILURE: Build failed with an exception.

* Where:
Build file '/opt/src/X-APM/x-apm-base/build.gradle' line: 110

* What went wrong:
A problem occurred evaluating project ':x-apm-base'.
> /opt/src/X-APM/local.properties (No such file or directory)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 38s
似乎缺少/opt/src/X-APM/local.properties这个文件？

**Comment by Tornaco** [comment]
@xseven007 对，这个文件定义了一些私密的属性。等我修复一下再试试！
