### ISSUE TITLE
gcm google连接失败

### ISSUE THREAD

**Issue by roch18** [Tornaco/X-APM#174]
1. What happened（现象）:
微信关闭后可以收到gcm消息，但是我发现 每隔三分钟跟Google play服务的连接就会断开，然后就收不到消息了

**Comment by Tornaco** [comment]
@roch18 你好，应用管理不负责维护与google的链接，推荐问问其他机油如何优化google的链接。

**Comment by heipidage** [comment]
修改ssr服务端的timeout

**Comment by roch18** [comment]
@heipidage 老哥哪里有修改timeout呀，我咋没看到这个设置呢，感谢

**Comment by heipidage** [comment]
一键的可能没有这个配置文件，一般在etc shadowscoks目录下

**Comment by Tornaco** [comment]
FYI
