### ISSUE TITLE
希望有app-release-debug.apk这个版本了

### ISSUE THREAD

**Issue by fhxu** [Tornaco/X-APM#176]
很多时候其他版本不能进入乖巧模式（微信、tim等），但是app-release-debug这个版本就可以，本来是靠着这个版本过日子了
可是现在没有看到 app-release-debug.apk 这个版本
如果方便的话，望能继续提供

**Comment by fhxu** [comment]
感谢回复
用了最新的 5.0.4-BETA4 版本，微信、tim都进入不了缓存！
手机是360 N4s 6.0.1系统

我需要提供什么吗？

**Comment by Tornaco** [comment]
@fhxu 需要xposed日志，新手教程有如何截取。

**Comment by Tornaco** [comment]
@fhxu 最好能把你设备的 frameworks/services.jar发给我看下。

**Comment by fhxu** [comment]
[services.jar.zip](https://github.com/Tornaco/X-APM/files/1958438/services.jar.zip)
来了

**Comment by Tornaco** [comment]
@fhxu 期待日志！！

**Comment by fhxu** [comment]
[services.odex.zip](https://github.com/Tornaco/X-APM/files/1958480/services.odex.zip)
来了
需要日志？
怎么提取？

**Comment by Tornaco** [comment]
@fhxu 按照教程 打开调试模式 复现 最后到xp里保存日志。

**Comment by fhxu** [comment]
已经打开调试，可xp里面没有日志

**Comment by fhxu** [comment]
是的，然后进了xp里面{日志）里面是空的，xp用的是85，xp app是3.0

**Comment by Tornaco** [comment]
@fhxu 好的，稍后我会发布一个截取日志的apk，需要root权限（发布完我会在这里回复）。你也可以自行下载一个类似的截取日志的logcat工具。
- 解决改问题日志是必须的。
- 无论用什么工具截取日志，都需要先打开应用管理调试模式。

**Comment by Tornaco** [comment]
https://www.coolapk.com/apk/com.pluscubed.matlog 试试这个。

**Comment by fhxu** [comment]
[2018-04-29-18-37-30.txt](https://github.com/Tornaco/X-APM/files/1958655/2018-04-29-18-37-30.txt)
来了

**Comment by Tornaco** [comment]
@fhxu
刚看到日志：

360OS 该处代码改过了，因此出现了不兼容。
请问能否给个适用于你机器的ROM链接，我需要下载完整ROM反编译。

```
/WifiTrafficPoller(1838): ADD_CLIENT: 16
04-29 18:36:49.612 E/X-APM-S-(1838): Error@lazyKill
04-29 18:36:49.612 E/X-APM-S-(1838): java.lang.NoSuchFieldError: com.android.server.am.ActiveServicesManager#mServiceMap
04-29 18:36:49.612 E/X-APM-S-(1838): 	at de.robv.android.xposed.XposedHelpers.findField(XposedHelpers.java:96)
04-29 18:36:49.612 E/X-APM-S-(1838): 	at de.robv.android.xposed.XposedHelpers.getObjectField(XposedHelpers.java:850)
04-29 18:36:49.612 E/X-APM-S-(1838): 	at github.tornaco.xposedmoduletest.xposed.service.am.ActiveServicesProxy.getMServiceMapField(Unknown Source)
04-29 18:36:49.612 E/X-APM-S-(1838): 	at github.tornaco.xposedmoduletest.xposed.service.am.ActiveServicesProxy.getServiceMapProxy(Unknown Source)
04-29 18:36:49.612 E/X-APM-S-(1838): 	at github.tornaco.xposedmoduletest.xposed.service.am.ActiveServicesProxy.getServiceRecords(Unknown Source)
04-29 18:36:49.612 E/X-APM-S-(1838): 	at github.tornaco.xposedmoduletest.xposed.service.am.ActiveServicesProxy.stopServicesForPackageUid(Unknown Source)
04-29 18:36:49.612 E/X-APM-S-(1838): 	at github.tornaco.xposedmoduletest.xposed.service.XAshmanServiceImpl$LazyServiceKiller.run(Unknown Source)
04-29 18:36:49.612 E/X-APM-S-(1838): 	at github.tornaco.xposedmoduletest.xposed.service.ErrorCatchRunnable.run(Unknown Source)
04-29 18:36:49.612 E/X-APM-S-(1838): 	at android.os.Handler.handleCallback(Handler.java:739)
04-29 18:36:49.612 E/X-APM-S-(1838): 	at android.os.Handler.dispatchMessage(Handler.java:95)
04-29 18:36:49.612 E/X-APM-S-(1838): 	at android.os.Looper.loop(Looper.java:148)
04-29 18:36:49.612 E/X-APM-S-(1838): 	at android.os.HandlerThread.run(HandlerThread.java:61)
04-29 18:36:49.626 W/Binder_9(2532): type=1400 audit(0.0:12767): avc: denied { ioctl } for path="socket:[144132]" dev="sockfs" ino=144132 ioctlcmd=7704 scontext=u:r:system_server:s0 tcontext=u:r:system_server:s0 tclass=unix_stream_socket permissive=0
```

**Comment by fhxu** [comment]
https://romdownload.360shouji.com/N4S625/073/ota_full_073_P0_stable_signed.zip
来了

**Comment by fhxu** [comment]
官方的073版本(就是我现在用的版本)默认是不支持xp框架的，所以用的是别人修改的版本

**Comment by Tornaco** [comment]
@fhxu 好的，稍后我编译新版本，里面加了新的运行日志，需要你帮忙测试下，还是要和之前一样截取日志。

**Comment by fhxu** [comment]
坐等

**Comment by Tornaco** [comment]
https://github.com/Tornaco/X-APM/releases/tag/5.0.5-BETA-FOR-360OS-DEBUG
链接再此处，如果编译服务器没问题的话，大概需要15分钟。

**Comment by fhxu** [comment]
[2018-05-01-20-37-35.txt](https://github.com/Tornaco/X-APM/files/1963772/2018-05-01-20-37-35.txt)
来了

**Comment by Tornaco** [comment]
@fhxu 请注意，先打开应用管理调试模式，在测试与保存日志：）

又提交了新的测试版本，还要麻烦测试一次：
https://github.com/Tornaco/X-APM/releases/tag/5.0.5-BETA-FOR-360OS-DEBUG%232

**Comment by fhxu** [comment]
[2018-05-01-21-32-15.txt](https://github.com/Tornaco/X-APM/files/1963886/2018-05-01-21-32-15.txt)
来了

**Comment by Tornaco** [comment]
@fhxu 麻烦重启下设备重新复现截取一次。

日志里什么都没看到。一定要先打开应用管理调试模式，在测试与保存日志。
谢谢。

**Comment by fhxu** [comment]
[2018-05-02-12-12-26.txt](https://github.com/Tornaco/X-APM/files/1965913/2018-05-02-12-12-26.txt)

来了

**Comment by Tornaco** [comment]
@fhxu QQ:1163397166加下把。还方便交流。
