### ISSUE TITLE
微信乖巧模式，通过GCM关联唤醒无法自动重新进入缓存

### ISSUE THREAD

**Issue by DoveKi** [Tornaco/X-APM#188]
微信乖巧模式后台能进缓存，但通过关联规则GCM收到消息唤醒后微信通知服务就一直驻留在后台，只有手动打开微信再切后台才会重新进缓存。
乖巧模式介绍里不是说接收GCM/FCM只会保留30秒么？
不知道是我少设置了什么，我只把微信加乖巧模式然后加了GCM关联规则，微信其他权限没修改，有什么办法能让微信收到GCM唤醒通知完后自动再进缓存么？

**Comment by Tornaco** [comment]
会修复这个问题。

**Comment by Tornaco** [comment]
@DoveKi 过几天修一下

**Comment by Tornaco** [comment]
@DoveKi 这是个bug 还没修复。😂

**Comment by DoveKi** [comment]
@Tornaco 先用GCM代收了，这个唤醒后驻留就跟没开乖巧模式一样了
