### ISSUE TITLE
微信 GCM 代收测试信息通知里的显示有语法有错误

### ISSUE THREAD

**Issue by JackieMium** [Tornaco/X-APM#211]
微信 GCM 代收模拟一条信息后显示

 > Hello XXX, this is 1-th message!

应该为 "this is THE 1- ST message!

改动的地方我加了大写了，一共两处。

**Comment by keith-xiong** [comment]
😂

**Comment by JackieMium** [comment]
@ivangreat 对，我想写 typo 但是这感觉又不算是 typo。标题怎么写都想了半天，不感觉现在的标题很长很复杂么 :joy：

**Comment by Maolaohei** [comment]
你是真的很严格啦。

**Comment by JackieMium** [comment]
@Maolaohei 看到了就顺手说一下嘛。提 Issue 不代表反对，是希望更好。

**Comment by Maolaohei** [comment]
只是调侃一下，并没有反对这样做的意思在里面。

**Comment by Maolaohei** [comment]
提出问题才能让app变得更好。

**Comment by Tornaco** [comment]
@JackieMium 非常支持😁
