### ISSUE TITLE
5.0.7-BETA版本反馈

### ISSUE THREAD

**Issue by Dreamy010** [Tornaco/X-APM#226]
5.0.7-BETA-RELEASE版本，工作在Android7.1.2, Flyme7会导致设备无法开机

**Comment by Tornaco** [comment]
@Dreamy010 好的，感谢！过几天回去了会沟通修复。

**Comment by Dreamy010** [comment]
@Tornaco 好的，非常感谢

**Comment by Tornaco** [comment]
@Dreamy010 
需要问几个问题
1. /data/system/tor/trace下有文件吗？ 有的话发给我。
2. 具体下载的是BETA几还记得吗？

**Comment by Dreamy010** [comment]
@Tornaco 咱是移植的魅蓝note6的rom😆

**Comment by Tornaco** [comment]
@Dreamy010 不会是小米机器把。。小米的话更好了，又能用miui/flyme

**Comment by Dreamy010** [comment]
@Tornaco zuk z2121，确实是miui9/flyme7

**Comment by Dreamy010** [comment]
@Tornaco 版本5.0.8不会卡机了

**Comment by Tornaco** [comment]
@Dreamy010 好的，感谢！
