### ISSUE TITLE
GCM代收的“模拟一条消息”通知提示出错

### ISSUE THREAD

**Issue by Zxlusersjly** [Tornaco/X-APM#254]
英语序数词后缀应为1st,2nd,3rd,4及之后均为th，而并非一直为st，数字后面应该亦不需要加短横线“-”。

**Comment by 1149663712** [comment]
可以的老铁，你英语一定很好，我也觉得那提示看起来有点怪怪的，其实直接写"1条测试消息"也够了

**Comment by Tornaco** [comment]
@1149663712 老铁，能帮忙翻一下其他文字么，这里有大片需要翻译：0
