### ISSUE TITLE
希望编辑组件功能增强

### ISSUE THREAD

**Issue by DoveKi** [Tornaco/X-APM#268]
像MAT增强模块那样阻止毒瘤应用自动重新激活组件
现在已经没用MAT，但应用管理不能阻止重新激活，所以增强模块还在用

**Comment by Tornaco** [comment]
@DoveKi  我的应用-设置-里可以设定。

![screenshot_20180530-111609-740](https://user-images.githubusercontent.com/23255526/40697006-f588b89e-63fa-11e8-9e46-e6f3b5edf9b1.jpg)

**Comment by Tornaco** [comment]
如果改设置无效请反馈。

**Comment by DoveKi** [comment]
这个功能藏在这个地方不合理啊。。。都没发现😂

**Comment by DoveKi** [comment]
@Tornaco 这个选项藏在这个地方不合理啊。。。这么久都没找到😂
