### ISSUE TITLE
对 限制 功能中多选菜单的建议

### ISSUE THREAD

**Issue by yttrium3** [Tornaco/X-APM#279]
目前在“自启限制”、”关联启动限制“、”返回强退“和”划卡强退“，点击+号后的选择界面中，右上角的三点菜单仅有一个选择全部的选项，建议直接将其更换为全选的图标，不再设置三点菜单。

**Comment by Tornaco** [comment]
感谢，会修改。另外长按两次选中的条目也可全选：）
