### ISSUE TITLE
gcm代收的通知图标以及声音

### ISSUE THREAD

**Issue by Julymycin** [Tornaco/X-APM#283]
1. What happened（现象）:
> 在黑底状态栏的情形下，状态栏的微信gcm通知图标是灰色的，并不是白色。另外，如果选择应用层面通知的话，自定义的通知声音失效了。
（另外请问一下，此app需要给予自启权限及常驻后台吗？）
2. Xposed logs（日志）:
```
LOG EXAMPLE
xxxxxxxx
xxxxxxxx
...
```
3. Device info（设备信息）: ``` Samsung S6 
 Android7.0```

4. Frequency（出现频率）: ```Always```

5. App version（版本）: ```latest-RELEASE```

**Comment by Tornaco** [comment]
@Julymycin Hi 第一个问题会找时间修复，第二，app无需维护，随便处置。
