### ISSUE TITLE
乖巧模式对于微信的问题

### ISSUE THREAD

**Issue by Aefer** [Tornaco/X-APM#293]

**Comment by ziyuedi** [comment]
以及，建议加入去除正在运行通知的功能

**Comment by Tornaco** [comment]
@ziyuedi 能否截个图看下通知栏。
可以试试 打开 进阶-拓展--禁止应用前台运行通知。

**Comment by ziyuedi** [comment]
![img_20180706_190805](https://user-images.githubusercontent.com/24859058/42375961-03fad872-8150-11e8-97ef-95370cf26a88.png)

**Comment by Tornaco** [comment]
@ziyuedi 试试这个 https://github.com/Tornaco/X-APM/releases/tag/5.1.3-BETA

**Comment by ziyuedi** [comment]
无效，正在运行通知依旧存在
以及，模块更新5.1.3-beta后提示兼容性遇到故障
还有，在某4.4oppo（coloros2.1）上也遇到了这种情况
And，在（本机）支付宝上也遇到了这种情况
![screenshot_2018-07-18-16-13-06](https://user-images.githubusercontent.com/24859058/42868929-20ebbc12-8aa6-11e8-9226-5b098a76a331.png)

**Comment by ziyuedi** [comment]
radio.log和dmesg.log均为0kb，没有tor/trace
[log_cat.log.zip](https://github.com/Tornaco/X-APM/files/2205041/log_cat.log.zip)
