### ISSUE TITLE
BUG: 划卡任意app，会直接把打开的冻结app也一起划卡清理掉。

### ISSUE THREAD

**Issue by qiuyouxin** [Tornaco/X-APM#310]
1. What happened（现象）: 

划卡任意app，会直接把打开的冻结app也一起划卡清理掉。酷安上也有人说有这个问题的。

2. Xposed logs（日志）:

[error.log](https://github.com/Tornaco/X-APM/files/2153980/error.log)

3. Device info（设备信息）: LG，Android 6.01。
4. Frequency（出现频率）: ```Always```

5. App version（版本）: ```5.1.1#3-RELEASE```

**Comment by Tornaco** [comment]
@qiuyouxin hao de

**Comment by qiuyouxin** [comment]
@Tornaco 问题已解决。
