### ISSUE TITLE
《关于移花接木》

### ISSUE THREAD

**Issue by Vulcan23** [Tornaco/X-APM#35]
移花接木无法去掉知乎APP的广告。

**Comment by Vulcan23** [comment]
知乎第一屏广告的Activity和知乎首页的Activity一模一样，没法替换。

**Comment by Vulcan23** [comment]
@Tornaco 知乎第一屏广告的活动和知乎首页的活动一模一样，没法替换。

**Comment by Tornaco** [comment]
@Vulcan23 Hi, 感谢反馈。现有方案无法解决该类问题，需要新的解决方案。
