### ISSUE TITLE
MIUI10 问题反馈

### ISSUE THREAD

**Issue by Dreamy010** [Tornaco/X-APM#368]
What happened（现象）:
激活应用管理会导致状态栏无法正常显示volte以及锁屏界面会显示无sim卡，取消激活应用管理两者正常显示

Frequency（出现频率）: Always

Device info（设备信息）:  MIUI10 8.7.19，Android7.1.2

App version（版本）: 5.1.4

**Comment by Tornaco** [comment]
@Dreamy010 有对系统app进行某些设置 吗？

**Comment by Dreamy010** [comment]
@Tornaco  非常感谢您，通过排除对系统应用处理，已解决。😆
