### ISSUE TITLE
歌曲分享失效

### ISSUE THREAD

**Issue by zjcjgjj** [Tornaco/X-APM#39]
用了应用管理以后发现歌曲分享到微信朋友圈显示微信安装，用虾米音乐，网易云音乐都这样。微信没有限制自启和关联启动，未作任何改变和限制，之后取消该模块重启后就可以分享了…

**Comment by Tornaco** [comment]
@zjcjgjj 检查下权限设定😏

**Comment by zjcjgjj** [comment]
权限未动，均打开




Allen







On Sat, Mar 10, 2018 at 3:11 PM +0800, "Potesta de Tornaco" <notifications@github.com> wrote:












@zjcjgjj 检查下权限设定😏

**Comment by Tornaco** [comment]
@zjcjgjj 请提供一份xposed日志，参考新手手册截取。

**Comment by zjcjgjj** [comment]
无法分享未对微信或音乐做处理






On Sat, Mar 10, 2018 at 5:51 PM +0800, "Potesta de Tornaco" <notifications@github.com> wrote:












@zjcjgjj 请提供一份xposed日志，参考新手手册截取。

**Comment by Tornaco** [comment]
请将日志传到github comment。
