### ISSUE TITLE
和 xposed edge 冲突

### ISSUE THREAD

**Issue by Bingjie-Huang** [Tornaco/X-APM#396]
**Describe the bug（现象描述）**
xposed  edge同时使用时，其底部边缘手势功能受阻。
关闭应用管理后正常。

**Version（发现问题的版本）:**
 - OS: And 8.0
 - Version v1.5.1

**Comment by e2rr** [comment]
我从一开始就是x-apm和xedge一起用的 没一年也有八九个月了 米6安卓7.12 加上现在还有米板4魔趣8.1 都没有你说的问题 请继续排查

**Comment by Bingjie-Huang** [comment]
好吧。我估计是禁用了应用导致的，可能是 magisk 或者 google play 服务
