### ISSUE TITLE
和包FC

### ISSUE THREAD

**Issue by rxzcums** [Tornaco/X-APM#40]
牛app，感谢。
但和包支付总是FC，禁了应用管理就好，图上是写轮眼显示出错的日志，请大佬查看
![screenshot_myandroidtools pro_20180310-162324](https://user-images.githubusercontent.com/11990604/37240015-ebfd3e0e-247f-11e8-83d6-c54285bbdefb.png)
![screenshot_myandroidtools pro_20180310-162346](https://user-images.githubusercontent.com/11990604/37240018-f284f834-247f-11e8-828a-c60dfecd1981.png)

**Comment by rxzcums** [comment]
对了，我是安卓8.1系统。

**Comment by Tornaco** [comment]
烦请先自己检查自己的设定。
这个问题我花了10分钟确认，基本80%是因为禁用了和宝支付的权限导致。

请检查--权限控制--和宝支付--应用列表/正在运行应用 权限！

感谢支持，但是为了节省彼此的精力，请一定无比先检查自我设定。
再次感谢。

**Comment by Tornaco** [comment]
如果是权限导致的请暂时开启其相应权限。并且关闭该issue。

**Comment by rxzcums** [comment]
致歉并致敬，群主果然牛。
经检查，果然是禁用了获取应用列表的权限，现在取消禁用后，不FC了，但变成卡启动logo了，日志中和包（hebao）有个AntiHijackService的服务，不知是否与此有关，烦请群主查看。关闭应用管理后正常。

附日志与点赞😁
[log_2018-03-10-21_40_46.txt](https://github.com/Tornaco/X-APM/files/1799430/log_2018-03-10-21_40_46.txt)

**Comment by rxzcums** [comment]
从乖巧模式中移除就可以了。鉴于乖巧模式是测试功能，不报bug，先close，非常感谢辛勤付出。
