### ISSUE TITLE
希望取消 Pie 的 Notification Listener

### ISSUE THREAD

**Issue by TragicLifeHu** [Tornaco/X-APM#417]
**Describe the bug**（现象描述）
当打开 EdXposed 日志时，可以看到一大半都是 X-APM：NotificationListener is not impl for android pie
这是无谓的消耗电量的行为

**To Reproduce**（如何复现）
在 Android Pie 打开 EdXposed 的日志即可看见

**Expected behavior**（期望结果）
把这个 log 直接去掉，既省电，又加快 EdXposed 效率

**Version**（发现问题的版本）:
5.1.7 - 5.2.1 （目前看来）

**Comment by Tornaco** [comment]
OK
