### ISSUE TITLE
关于乖巧模式

### ISSUE THREAD

**Issue by zzw6776** [Tornaco/X-APM#44]
首先感谢提供这么方便的软件,然后有个小疑问
对应用启用乖巧模式后,用黑域或者自带的查看运行服务功能都还能看到程序有服务在执行,本来以为是没效果,但是后来发现被乖巧模式的支付宝不能被应用唤起,说明服务应该是被限制了的,但是用黑域看服务还是存在,有办法确定这个模式有没有其效果吗

**Comment by Tornaco** [comment]
容我思考一下子~
