### ISSUE TITLE
Yuantiku v8.0.1 FC

### ISSUE THREAD

**Issue by sino1641** [Tornaco/X-APM#5]
What happened:
X-APM causes yuantiku app FC.
And yuantiku runs after I turned X-APM off in xposed installer.
I have also tried anything I could for a student who doesn't know much about android programming. 

Logs:
The following pictures are app crash record, android logcat and X-APM debugging mode logs.
![c](https://cdn.reimu.net/uploads/2018/02/Screenshot_20180212_222542~01.png)
![l](https://cdn.reimu.net/uploads/2018/02/result_2018_02_12_22_31_55~01~01.png)
![l](https://cdn.reimu.net/uploads/2018/02/Notes_20180212_225652.png)

Device info:
Oneplus One LOS 14.1

Frequency:
Always
App version:
4.6.8-FINAL

//I found that this project  is desperated,but I hope @Tornaco can teach me how to do.
//Thanks for forgiving my poor English!

**Comment by Tornaco** [comment]
Hey I think I could help if you can provide me the X-APM configs. You can share by the "backup" feature in "通用设置---数据备份"。
Also you can try to fix this issue by:
1. Do not restrict any app permission for yuantiku (Check 权限控制)。
2. Do not add to "乖巧模式" list。
If this not work, please just send me your configs.

BTW，I‘ve tested this app on my ZUK Z1/LOS14.1, It is OK at first launch. but when I disable all it's permission by "权限控制", I found it crash too, and got same log when your's. this means it need some permissions you did not given.

Good luck.

**Comment by sino1641** [comment]
Thanks for you reply!
It really works when I granted all permissions manually.
One more thing, happy spring festival! :D

**Comment by sino1641** [comment]
Thanks for you reply!
It really works when I granted all permissions manually.
One more thing, happy spring festival! :D

**Comment by sino1641** [comment]
Thanks for you reply!
It really works when I granted all permissions manually.
One more thing, happy spring festival! :D

**Comment by sino1641** [comment]
Thanks for you reply!
It really works when I granted all permissions manually.
One more thing, happy spring festival! :D

**Comment by sino1641** [comment]
Thanks for you reply!
It really works when I granted all permissions manually.
One more thing, happy spring festival! :D

**Comment by sino1641** [comment]
Thanks for you reply!
It really works when I granted all permissions manually.
One more thing, happy spring festival! :D

**Comment by sino1641** [comment]
Thanks for you reply!
It really works when I granted all permissions manually.
One more thing, happy spring festival! :D

**Comment by sino1641** [comment]
Thanks for you reply!
It really works when I granted all permissions manually.
One more thing, happy spring festival! :D
