### ISSUE TITLE
关于一个不知是否好实现的功能：GCM唤醒加强

### ISSUE THREAD

**Issue by loonglin1** [Tornaco/X-APM#55]
就是像绿色守护一样，收到GCM推送后，会增强唤醒该应用，比如GCM功能半残的微信就很需要该功能。

可以的话希望开发者增加这个功能😙

**Comment by Tornaco** [comment]
@loonglin1 Thanks,会优先着重考虑该功能

**Comment by loonglin1** [comment]
@Tornaco 期待xD

**Comment by Tornaco** [comment]
@loonglin1

**Comment by Tornaco** [comment]
Solution:

添加GCM(FCM)关联启动规则支持：
允许GCM(FCM)唤醒所有APP：```ALLOW GCM *```
允许GCM(FCM)唤醒微信：```ALLOW GCM com.tencent.mm```

拒绝的规则以此类推。

**Comment by Tornaco** [comment]
@loonglin1 请帮忙测试是否符合要求，如果不符合要求请务必提供日志。

https://github.com/Tornaco/X-APM/releases/tag/4.9.5-BETA
北京时间15:10会生成apk。

多谢。

**Comment by loonglin1** [comment]
@Tornaco 好的，是直接使用（默认启用所有），还是新增一个单独选项将需要gcm、fcm唤醒的APP加入到列表才能生效呢

**Comment by Tornaco** [comment]
@loonglin1 请参考上方规则设定。

**Comment by loonglin1** [comment]
@Tornaco 原来github的签名和play版的签名不一样-_-||

我说怎么老安装不上，稍等我核心破解一下

CN=Android
OU=Android
O=Google Inc.
L=Mountain View
ST=California
C=US

**Comment by Tornaco** [comment]
@loonglin1 对，Play版有二次签名

**Comment by loonglin1** [comment]
@Tornaco （绿色守护已关闭，）添加了gcm规则，GCM心跳正常。但微信无法唤起，通知栏也没有任何通知。（微信不在关联启动列表中），telegram通知栏闪现一下然后被阻止了【记录：已经阻止12次，最近阻止3 分钟前， 阻止原因 USER_DENIED，妄图启动者 Android系统。】（telegram已限制关联启动）。

在使用绿色守护时，微信则可以直接跳出登录页面（我测试的是在电脑登录微信。）

GCM STATUS  ：
03-20 16:01:32.233 net=1: Sent Close
03-20 16:01:32.273 net=1: Close err:FIN time:289
03-20 16:01:40.168 net=1: Connected
03-20 16:02:07.260 net=1: Sent com.android.chrome
03-20 16:02:32.034 net=1: Received com.tencent.mm 0:1521532953637296%c5fe9776f9fd7ecd []
03-20 16:02:33.773 net=1: Broadcasted com.tencent.mm result=0 time=1727
03-20 16:02:49.218 net=1: Sent com.android.chrome
03-20 16:04:01.542 net=1: Received com.tencent.mm 0:1521533043065052%c5fe9776f9fd7ecd []
03-20 16:04:01.576 net=1: Broadcasted com.tencent.mm result=0 time=21
03-20 16:06:02.481 net=1: Sent Close
03-20 16:06:02.499 net=1: Close err:FIN time:262
03-20 16:06:13.281 net=1: Connected
03-20 16:06:16.398 net=1: Received com.tencent.mm 0:1521533178093864%c5fe9776f9fd7ecd []
03-20 16:06:16.465 net=1: Broadcasted com.tencent.mm result=0 time=45
03-20 16:08:17.422 net=1: Sent Close
03-20 16:08:17.430 net=1: Close err:FIN time:124
03-20 16:08:28.091 net=1: Connected
03-20 16:08:29.522 net=1: Received org.telegram.messenger 0:1521533311223420%8eeb79b0f9fd7ecd []
03-20 16:10:30.661 net=1: Sent Close
03-20 16:10:30.668 net=1: Close err:FIN time:122
03-20 16:10:36.650 net=1: Connected
03-20 16:11:05.362 net=1: Received com.tencent.mm 0:1521533467108989%c5fe9776f9fd7ecd []
03-20 16:11:05.395 net=1: Broadcasted com.tencent.mm result=0 time=19
03-20 16:12:55.326 net=1: Sent com.android.chrome
03-20 16:13:34.393 net=1: Sent com.android.chrome
03-20 16:15:34.678 net=1: Sent Close
03-20 16:15:34.687 net=1: Close err:FIN time:298
03-20 16:15:40.871 net=1: Connected
03-20 16:17:41.446 net=1: Sent Close
03-20 16:17:41.456 net=1: Close err:FIN time:120
03-20 16:17:47.836 net=1: Connected
03-20 16:17:48.049 net=1: Sent com.android.chrome
03-20 16:18:02.533 net=1: Received com.tencent.mm 0:1521533884076114%c5fe9776f9fd7ecd []
03-20 16:18:02.599 net=1: Broadcasted com.tencent.mm result=0 time=45
03-20 16:18:32.459 net=1: Sent com.android.chrome
03-20 16:19:14.305 net=1: Received org.telegram.messenger 0:1521533955883799%8eeb79b0f9fd7ecd []
03-20 16:19:20.795 net=1: Sent com.android.chrome
03-20 16:19:54.060 net=1: Sent com.android.chrome
03-20 16:20:41.032 net=1: Sent com.android.chrome
03-20 16:21:41.228 net=1: Sent com.android.chrome
03-20 16:23:18.974 net=1: Sent com.android.chrome
03-20 16:24:44.543 net=1: Sent com.android.chrome
03-20 16:25:28.443 net=1: Received org.telegram.messenger 0:1521534330106589%8eeb79b0f9fd7ecd []
03-20 16:25:57.276 net=1: Received com.tencent.mm 0:1521534359066985%c5fe9776f9fd7ecd []
03-20 16:25:57.322 net=1: Broadcasted com.tencent.mm result=0 time=33
03-20 16:26:39.206 net=1: Sent com.android.chrome
03-20 16:28:38.728 net=1: Sent com.android.chrome
03-20 16:28:53.191 net=1: Sent com.android.chrome
03-20 16:29:36.610 net=1: Sent com.android.chrome
03-20 16:30:35.819 net=1: Sent com.android.chrome

**Comment by Tornaco** [comment]
@loonglin1 OK 感谢，请同时截取一份xp日志：https://github.com/Tornaco/X-APM/wiki/Bug%E4%B8%8A%E6%8A%A5

**Comment by Tornaco** [comment]
@yinheng

**Comment by loonglin1** [comment]
@Tornaco 啊呀，不好意思，这样提交日志又多了一个 issues

**Comment by Tornaco** [comment]
@loonglin1 可以。

**Comment by loonglin1** [comment]
![screenshot_2018-03-20_17-08-31 637_github tornaco xposedmoduletest](https://user-images.githubusercontent.com/26075749/37645290-62ec2136-2c61-11e8-81f2-91947ec1071c.jpg)
请教个问题，为何微信没有加入自启限制（限制了开机自启），还会被应用管理阻止呢？

**Comment by Tornaco** [comment]
@loonglin1 请截图看下微信的单项设定，以及关联启动规则设定。

**Comment by loonglin1** [comment]
@Tornaco 
谢谢，请看图。虽然把微信加入到返回强退、划卡强退，但是这两个功能总开关是关闭的（未启用）



![screenshot_2018-03-20_17-15-22 242_github tornaco xposedmoduletest](https://user-images.githubusercontent.com/26075749/37645678-82728c92-2c62-11e8-8c93-bb6cfad73c35.jpg)
![screenshot_2018-03-20_17-16-01 707_github tornaco xposedmoduletest](https://user-images.githubusercontent.com/26075749/37645688-8bea7c1c-2c62-11e8-8b26-533bdb99dd2b.jpg)
![screenshot_2018-03-20_17-16-33 651_github tornaco xposedmoduletest](https://user-images.githubusercontent.com/26075749/37645700-91bf06ee-2c62-11e8-9a71-7620517316ba.jpg)

**Comment by Tornaco** [comment]
好的，建议暂时再检查下，我这里测试未发现该问题。
明天我会提交一个调试版本，会包含完整的阻止信息。到时候在测试一次。谢谢。

**Comment by loonglin1** [comment]
@Tornaco 好的

**Comment by Tornaco** [comment]
错误分析1:  Refer@https://github.com/phonegap/phonegap-plugin-push/issues/211
被forcestop后app无法接收到GCM。
方案：当接收到GCM intent时，主动启动该app进程。

错误分析2: 此时如果该app被限制了关联启动，可能依然无法启动相关服务。
方案：当接收到GCM intent时，留给该App短暂的时间允许其处理该时间（24s，此时不限制其关联启动）。

综合起来，以微信为例，实现增强GCM的用户操作方案如下：
1. 添加关联启动规则 ```ALLOW GCM com.tencent.mm```。（允许接收GCM事件）。
2. 添加关联启动规则 ```ALLOW GCMENHANCE com.tencent.mm```。（允许系统帮助启动（唤醒）该App）。

此时用户依然可以将微信加入 划卡强退，关联启动限制，锁屏清理，而不影响GCM消息推送。

**Comment by Tornaco** [comment]
![_20180321132444](https://user-images.githubusercontent.com/23255526/37695566-4aef1232-2d0b-11e8-992a-2d8c120aac8a.jpg)

微信测试结果。

**Comment by loonglin1** [comment]
@Tornaco  已更新到beta4， 微信已加入关联启动，规则也已配置，成功唤醒微信后台服务，但仍旧不在前台/通知栏显示登录提示。

![screenshot_2018-03-21_14-52-38 645_com android settings](https://user-images.githubusercontent.com/26075749/37697423-ca2443a4-2d17-11e8-96a8-938be0bbf819.jpg)
![screenshot_2018-03-21_14-53-00 593_github tornaco xposedmoduletest](https://user-images.githubusercontent.com/26075749/37697425-d2a10c74-2d17-11e8-9584-c0ad62168772.jpg)
![screenshot_2018-03-21_14-53-16 097_github tornaco xposedmoduletest](https://user-images.githubusercontent.com/26075749/37697433-da95061a-2d17-11e8-88fe-e9a11a8f1f0b.jpg)

**Comment by Tornaco** [comment]
@loonglin1 OK，检查了下代码，是一个参数传递失误了。我提交了新版本，请继续测试BETA5

**Comment by loonglin1** [comment]
@Tornaco 

感谢开发者！现在好像很不错，接收到gcm可以在前台唤醒微信了(๑•̀ㅂ•́)و✧。

只是从beta4更新到beta5，我需要在xposed installer里重新激活才能生效。【机型：oneplus one；ROM：Dirty Unicorns ;Android版本：8.1.0】


不知道和我的系统在之前莫名卡死的事件（卡死，然后我强制重启了）有没有关系，/data/system/tor/trace/ 下提取的日志如附件【格式不对传不上来，我压缩了一下】
[SYSTEM_ERROR_TRACE-03-21-17-13-29.zip](https://github.com/Tornaco/X-APM/files/1832635/SYSTEM_ERROR_TRACE-03-21-17-13-29.zip)

**Comment by Tornaco** [comment]
@loonglin1 初步看日志应该是系统本身的bug

**Comment by 250662772** [comment]
老大，华为手机自带的应用分身微信，怎么添加关联规则才能走gcm？

**Comment by loonglin1** [comment]
@250662772 我也不懂，我帮你@开发者

请看前面一楼的问题 @Tornaco

**Comment by heipidage** [comment]
有个问题，当微信处于休眠状态时，无法弹出通知，划掉反而可以…看能否解决，暂时只有放电池优化白名单解决。

**Comment by sxml** [comment]
@heipidage 同样问题
