### ISSUE TITLE
EX Kernel Manager的自启问题

### ISSUE THREAD

**Issue by ssshhhnnn** [Tornaco/X-APM#67]
EX Kernel Manager需要开机启动来做一些配置，开启模块后不能够开机启动，然而我并没有对它限制自启和关联启动，系统也没有限制软件；禁用模块后开机自启正常。这也是概率性问题，极少数情况下，开启模块后它也能开机自启。

**Comment by Tornaco** [comment]
@ssshhhnnn 请提供日志以及详细说明，例如ex kernel是什么，系统版本等。感谢。

**Comment by ssshhhnnn** [comment]
[error.log](https://github.com/Tornaco/X-APM/files/1845097/error.log)
@Tornaco  日志已上传
ex kernel manager是一个内核调校软件，它可以管理CPU和GPU，提升或者固定CPU/GPU频率。

**Comment by ssshhhnnn** [comment]
[error(1).log](https://github.com/Tornaco/X-APM/files/1845125/error.1.log)
之前的日志是手机重启后软件没有正常运行的。这个是正常的

**Comment by Tornaco** [comment]
@ssshhhnnn 好的，麻烦再传一张 EX的单项配置截图。我这里复现试试。

**Comment by ssshhhnnn** [comment]
![screenshot_2018-03-26-10-13-20-468_flar2 exkernelmanager](https://user-images.githubusercontent.com/34705923/37884525-d25f4b78-309f-11e8-867f-e43393652a56.png)
![screenshot_2018-03-26-10-13-06-833_flar2 exkernelmanager](https://user-images.githubusercontent.com/34705923/37884536-dea343f8-309f-11e8-9c2e-cb1ac1bd2b4b.png)
![screenshot_2018-03-26-10-12-47-096_flar2 exkernelmanager](https://user-images.githubusercontent.com/34705923/37884539-e4e664c0-309f-11e8-9acc-f18242d35c95.png)
@Tornaco 大概是这样的， [https://github.com/yc9559/cpufreq-interactive-opt/blob/master/20180317-balanced.md](url) 这个是配置作者的原贴

**Comment by Tornaco** [comment]
@ssshhhnnn

**Comment by Tornaco** [comment]
@ssshhhnnn 应用管理，我的应用 ex 单项配置

**Comment by ssshhhnnn** [comment]
![screenshot_2018-03-26-10-51-07-889_github tornaco xposedmoduletest](https://user-images.githubusercontent.com/34705923/37884651-973e498a-30a0-11e8-8d64-dea5e116af2c.png)
@Tornaco

**Comment by Tornaco** [comment]
@ssshhhnnn 多谢，请继续使用该版本测试，需要打开工具箱--调试模式后，复现（重启）开机过1分钟后进入xp截取日志。另外你的系统是8.x？还是N？https://github.com/Tornaco/X-APM/releases/tag/4.9.6-BETA2

**Comment by ssshhhnnn** [comment]
@Tornaco  好的，晚些时候我再来反馈，多谢。系统是7.0.1

**Comment by ssshhhnnn** [comment]
@Tornaco 更新之后 经过N多次重启，开启调试模式之后几乎没有复现，即使关闭了也是小概率复现了。所以我再观望几天，如果又频繁复现了，再来反馈。感谢开发者，辛苦了 :-)
