### ISSUE TITLE
关联规则设置失败

### ISSUE THREAD

**Issue by MagiciSource** [Tornaco/X-APM#68]
我设置了关联规则允许小米服务框架启动任意应用，但是点通知栏还是不能唤醒应用

**Comment by MagiciSource** [comment]
![image](https://user-images.githubusercontent.com/15188279/37873955-c2ee202a-3058-11e8-8114-5c8dd0df6d26.png)
![image](https://user-images.githubusercontent.com/15188279/37873958-c857e1a4-3058-11e8-8f85-8f214d10d3de.png)

**Comment by Tornaco** [comment]
@MagiciSource 麻烦试试496BETA https://github.com/Tornaco/X-APM/releases/tag/4.9.6-BETA

**Comment by MagiciSource** [comment]
阻止记录里的妄图启动者变成了软件自己，能不能加个规则可以允许自己启动自己😂😂还有安卓系统加了规则也还在阻止记录里，虽然好像没啥影响

**Comment by Tornaco** [comment]
@MagiciSource ”规则可以允许自己启动自己“ 可以试试手动添加 ALLOW A A

**Comment by Tornaco** [comment]
@MagiciSource A 代表该应用包名。

**Comment by MagiciSource** [comment]
我是想一次允许全部的，一个一个加有点难受😂😂

**Comment by Tornaco** [comment]
@MagiciSource 先加一个试试 是否可以解决该问题？

**Comment by MagiciSource** [comment]
可以解决~试了俩应用没问题

**Comment by Tornaco** [comment]
@MagiciSource OK，请等待新版。

**Comment by MagiciSource** [comment]
期待~对了，强制打盹没有屏蔽运动检测开关，不知道实际做了没有

**Comment by Tornaco** [comment]
@MagiciSource 并没有屏蔽运动检测功能。

**Comment by MagiciSource** [comment]
好做的话不如加上

**Comment by Tornaco** [comment]
@MagiciSource 请新建一个issue。可能需要按照issue顺序等待：）

**Comment by Tornaco** [comment]
@MagiciSource 请添加规则 ALLOW THIS THIS

**Comment by MagiciSource** [comment]
不行……被阻止了

**Comment by Tornaco** [comment]
@MagiciSource 继续试试BETA4

**Comment by MagiciSource** [comment]
这版好着呢
