### ISSUE TITLE
强制打盹屏蔽运动检测

### ISSUE THREAD

**Issue by MagiciSource** [Tornaco/X-APM#71]
希望强制打盹功能可以屏蔽运动检测

**Comment by Tornaco** [comment]
@MagiciSource 请测试 BETA3版本 https://github.com/Tornaco/X-APM/releases/tag/4.9.6-BETA3

**Comment by MagiciSource** [comment]
没有apk啊😂😂

**Comment by Tornaco** [comment]
@MagiciSource 10分钟
