### ISSUE TITLE
关于自选编译

### ISSUE THREAD

**Issue by TinkMingKing** [Tornaco/X-APM#75]
不能自选编译了么，好像缺文件啊……

**Comment by Tornaco** [comment]
@TinkMingKing 请稍等，晚些时候会做一次检查：）

**Comment by Tornaco** [comment]
@TinkMingKing 麻烦把编译日志贴上来看下。

**Comment by Tornaco** [comment]
./gradlew app:assembleRelease
请使用上述command编译。
