### ISSUE TITLE
关于快速设置的bug

### ISSUE THREAD

**Issue by TinkMingKing** [Tornaco/X-APM#77]
快速设置的“显示当前活动”瓷块激活后始终为“活跃”状态，但是功能能够正常开关，感觉只是一个很小的逻辑bug，但是使用起来还是有些不舒服

再就是，长按没有设置跳转活动，默认开启系统应用管理界面，我认为设置跳转到移花接木界面会比较合理，因为通常使用“显示当前活动”，多半是为了替换活动
只需要在活动的intent-filter中添加
`<action android:name="android.service.quicksettings.action.QS_TILE_PREFERENCES" />`
即可

**Comment by Tornaco** [comment]
@TinkMingKing OK，感谢。

**Comment by Tornaco** [comment]
Fixed since 4.9.8
