### ISSUE TITLE
易用性小建议：能否增加通知栏强制停止app的快捷操作。

### ISSUE THREAD

**Issue by qiuyouxin** [Tornaco/X-APM#78]
某些app在有些时候，在最近任务不会出现，但确实有停止的需要，所以希望能有添加app运行后，在通知栏弹出强制停止的快捷操作。

**Comment by Tornaco** [comment]
@qiuyouxin 建议 打开--我的应用-XXX-Manifest&Condig 强制最近任务显示。或者使用 返回键强行停止 功能，如果以上均不满足需求，在考虑是否添加如上功能。

**Comment by qiuyouxin** [comment]
在某些情况下，app界面没有打开过， 那么在 Manifest 这里设置 强制显示，应该是没用的。 有时候需要通过 拉起 某app 的服务， 而这app没有打开界面 ，就需要在通知栏了。

感觉就有点像 绿色守护 的通知栏操作一样。 如果有了这个 易用性操作， 完全可以替代其他同类应用。

**Comment by yinheng** [comment]
https://github.com/Tornaco/X-APM/commit/e890352895c833f9c04c2fae4bc5684ebca74c48

**Comment by Tornaco** [comment]
Fix since 4.9.8-BETA2
