### ISSUE TITLE
建议添加 屏蔽特定程序toast功能

### ISSUE THREAD

**Issue by Maolaohei** [Tornaco/X-APM#93]
因为屏蔽了TIM部分组件,导致TIM频繁弹出toast,影响使用体验,特建议.

**Comment by Tornaco** [comment]
@Maolaohei 
请使用 权限管理--显示问候语 权限进行控制。

**Comment by Maolaohei** [comment]
原来叫问候语说，我还纳闷问候语是什麽东西，结果是toast。
