### ISSUE TITLE
进程缓存里面还有个别APP自动启动

### ISSUE THREAD

**Issue by 250662772** [Tornaco/X-APM#96]
刚看到运行进程缓存里面有王者荣耀和蜜蜂骑行APP运行，都已经禁止和关联启动了，不知道被什么程序给启动了，关了节电模式，也看不到这两个程序被什么进程给启动了，希望增加个日志能看到什么时候被那些程序启动了

**Comment by Tornaco** [comment]
可以，会增加这类日志。

**Comment by Tornaco** [comment]
关联启动--阻止（允许）记录 可以查看日志。
