### ISSUE TITLE
一些建议希望开发者能够考虑下：）

### ISSUE THREAD

**Issue by loonglin1** [Tornaco/X-APM#97]
1. 在导入组件配置（MyAndroidTools同款功能）时希望可以记住打开位置（结束应用管理xposed前台进程时可销毁位置记录）。

2. 更进一步，可以的话希望增加组件配置的一键备份还原功能。

3. 作者出于安全考虑而禁用了关联启动规则等功能的数据备份。可以的话还是希望增加一个隐藏开关或者带安全提示的开关来开启特殊功能的备份。（这里有个小问题：钛备份并不能备份应用管理xposed全部数据是因为钛备份、xp框架的限制还是应用管理本身禁止其备份数据呢？）

**Comment by Maolaohei** [comment]
回复:这个问题 应该 是应用管理 的 一部分数据 没有按照套路来,又因为钛备份是按照套路备份的,所以就没有备份到.有个 L 工具箱 也是如此,钛备份不能备份数据.

建议:如果要加入这个特殊功能的化,这个特殊的功能的开启方法,可以选用通过快速点击开发者1分钟50下来激发,避免了误操作.

**Comment by Tornaco** [comment]
这个问题原因是存储路径不是按照第三方应用来设计的。
一开始设计这个app的时候，没考虑做这么多功能，为了方便应用层和框架层交互，数据均存储在系统设置里（SettingsProvider）。
因此第三方备份无法读取。

再后来功能变多后，也设计了相应的独立的数据存储方案，但是考虑到数据迁移可能需要清除用户的设定数据，旧数据（大部分开关）并没有进行迁移。

因此现在的数据存放还是以系统设置为主，备份应用无法进行备份。

// 现在确实需要一套完整的数据迁移整合方案，后续会着重考虑该方向。

感谢!

**Comment by Tornaco** [comment]
@loonglin1 1条可否来个演示，个人使用该类app很少，因此没有这类经验。感谢。

**Comment by loonglin1** [comment]
@Tornaco 我第一条的意思是希望可以记住上次打开备份文件的位置。就是说，我想要编辑“百度输入法”的组件（阉割），我从备份导入，路径比如是/sdcard/backup/

当导入“百度输入法”的组件配置备份成功后，我又要导入“百度网盘”的组件备份，那么再次点击“导入服务配置”等功能选项时，希望能够直接定位到/sdcard/backup/


![gif-180408_145954](https://user-images.githubusercontent.com/26075749/38464280-abfb128e-3b3d-11e8-9b08-81a76c8fbc36.gif)

**Comment by Tornaco** [comment]
@loonglin1 好的

**Comment by Tornaco** [comment]
Fix 1. since 4.9.8
